<a href="https://colab.research.google.com/github/Aishwarya-114/TNSIF--AIML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (Numerical Python) is a powerful open-source Python library used for numerical computing.

# List of Functions and Their Usage

 **1)np.array()**-	Create an array

**2)np.arange(start, stop, step)**- Create array with range of values

**3)np.zeros((m,n))**-	Create array filled with zeros

**4)np.ones((m,n))**-	Create array filled with ones

**5)np.eye(n)**-	Identity matrix

**6)np.linspace(start, stop, num)**-	Create evenly spaced numbers

**7)np.random.rand(m,n)**-	Random numbers between 0 and 1

**8)np.shape**-	Get dimensions of array

**9)np.reshape()**-	Reshape array

**10)np.sum(), np.mean(), np.std()**-	Aggregation functions

**11)np.min(), np.max(), np.argmin(), np.argmax()**-	Min/Max values & indices

***12)np.dot(), np.matmul()***-	Matrix multiplication

**13)np.transpose()**-	Transpose of matrix

**14)np.sort()**- Sorting array

In [3]:
import numpy as np
arr1=([1,2,3,4])
print(arr1)
arr2=([5,6,7,8])
print(arr2)

[1, 2, 3, 4]
[5, 6, 7, 8]


In [5]:
import numpy as np
arr1 = ([1,2,3,4])
print(arr1)
arr2 = ([1,2,3,4],[5,6,7,8])
print(arr2)

arr = np.array([1,2,3])
print(ar)

print(arr)


zero = np.zeros((2,3))
print('zero array : ',zero)

one = np.ones((3,3))
print('ones array : ',one)

identity = np.eye(4,4)
print(identity)

ls = np.linspace(1,3,5)
print(ls)

randnum = ((np.random.rand(2,3))*10).astype(int)
print(randnum)

#dimentions of arr2
ashp = np.shape(arr2)
print(ashp)

arr = np.arange(2,10).reshape(4,2)
print(arr)




[1, 2, 3, 4]
([1, 2, 3, 4], [5, 6, 7, 8])
[1 2 3]
[1 2 3]
zero array :  [[0. 0. 0.]
 [0. 0. 0.]]
ones array :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1.  1.5 2.  2.5 3. ]
[[2 9 6]
 [9 9 5]]
(2, 4)
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [6]:
array1 = ([1,2,3,4],[5,6,7,8])
array2 = ([4,6,8,3],[2,5,7,9])
addition = np.sum(array2)
print(addition)

Mean = np.mean(array1)
print(Mean)

standard = np.std(array1)
print(standard)

Min = np.min(array1)
print(Min)
Max = np.max(array1)
print(Max)

ArgMin = np.argmin(array1)
print(ArgMin)

ArgMax = np.argmax(array1)
print(ArgMax)

X = np.array(([3,4],[5,6]))
Y = np.array(([8,9],[6,7]))
Dot = np.dot(X,Y)
print(Dot)

mat = np.arange(2,10).reshape(2,4)
print(mat)
print(mat.T)

sorts = np.sort(array2)
print(sorts)

44
4.5
2.29128784747792
1
8
0
7
[[48 55]
 [76 87]]
[[2 3 4 5]
 [6 7 8 9]]
[[2 6]
 [3 7]
 [4 8]
 [5 9]]
[[3 4 6 8]
 [2 5 7 9]]


In [7]:

# Importing NumPy
import numpy as np

# Creating Arrays
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1, 2, 3], [4, 5, 6],[9,10,11],[11,12,13]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# Array with specific values
zeros = np.zeros((3,4))
ones = np.ones((2,3))
identity = np.eye(5)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

# Range and linspace
arange_arr = np.arange(1, 45, 2)
linspace_arr = np.linspace(1, 2, 4)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

# Random numbers
rand_arr = np.random.rand(2,3)
print("Random Array:\n", rand_arr)
otp =( (rand_arr*1000000)).astype(int)
print("Random Array:\n", otp)


1D Array: [1 2 3 4 5 6]
2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]
 [11 12 13]]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Arange: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43]
Linspace: [1.         1.33333333 1.66666667 2.        ]
Random Array:
 [[0.17583897 0.71812988 0.41019036]
 [0.45703598 0.69165079 0.67466032]]
Random Array:
 [[175838 718129 410190]
 [457035 691650 674660]]


In [8]:
# Example 1: Reshape and Transpose
matrix = np.arange(1, 13).reshape(4,3)
print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)

# Example 2: Mathematical operations
arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Array + 5:", arr - 5)
print("Array squared:", arr ** 2)

# Example 3: Aggregate Functions
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

# Example 4: Matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n", np.dot(A,B))

# Example 5: Sorting
unsorted = np.array([3,1,4,1,5,9])
print("Sorted Array:", np.sort(unsorted))


Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Original Array: [10 20 30 40]
Array + 5: [ 5 15 25 35]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]


# **TASKS**

1.create a numpy arr conatining number from 1 to 20 using inbuilt function

In [9]:
import numpy as np
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2.Create an arr of all zeroes with 10 elements and convert it to matrix

In [11]:
arr = np.zeros(10)
print("Array:")
print(arr)

# Convert the array into a 2x5 matrix
matrix = arr.reshape(2, 5)
print("\nMatrix:")
print(matrix)

Array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Matrix:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


3.create an arr containing even numbers from 2 to 20

In [12]:
arr3 = np.arange(2, 21, 2)
print(arr3)

[ 2  4  6  8 10 12 14 16 18 20]


4.create an arr find number of dimentions , shape,size,datatype and multiply every element by 2

In [14]:
import numpy as np

# Create an array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Number of dimensions
print("Number of dimensions:", arr.ndim)

# Shape of the array
print("Shape:", arr.shape)

# Size of the array
print("Size:", arr.size)

# Data type of the array
print("Data type:", arr.dtype)

# Multiply every element by 2
result = arr * 2
print("Array after multiplying by 2:")
print(result)

Number of dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int64
Array after multiplying by 2:
[[ 2  4  6]
 [ 8 10 12]]


5.create 1d arr and find sum , mean , max,min

In [15]:
arr5 = np.array([10, 20, 30, 40, 50],)
print(arr5)
print("sum =", np.sum(arr5))
print("mean =", np.mean(arr5))
print("Max =", np.max(arr5))
print("Min =", np.min(arr5))
print("std=",np.std(arr5))


[10 20 30 40 50]
sum = 150
mean = 30.0
Max = 50
Min = 10
std= 14.142135623730951
